// Code generated by 'micro gen' command.
// DO NOT EDIT!

package api

import (
	tp "github.com/henrylee2cn/teleport"

	"github.com/xiaoenai/tp-micro/examples/project/args"
	"github.com/xiaoenai/tp-micro/examples/project/logic"
)

// Home comment...
func Home(ctx tp.PullCtx, arg *struct{}) (*args.HomeResult, *tp.Rerror) {
	return logic.Home(ctx, arg)
}

// Math controller
type Math struct {
	tp.PullCtx
}

// Divide handler
func (m *Math) Divide(arg *args.DivideArg) (*args.DivideResult, *tp.Rerror) {
	return logic.Math_Divide(m.PullCtx, arg)
}

// Stat comment...
func Stat(ctx tp.PushCtx, arg *args.StatArg) *tp.Rerror {
	return logic.Stat(ctx, arg)
}
