// Code generated by 'micro gen' command.
// DO NOT EDIT!

package api

import (
	"github.com/henrylee2cn/erpc/v6"

	"github.com/xiaoenai/tp-micro/examples/project/args"
	"github.com/xiaoenai/tp-micro/examples/project/logic"
)

// Home handler
func Home(ctx erpc.CallCtx, arg *args.EmptyStruct) (*args.HomeResult, *erpc.Status) {
	return logic.Home(ctx, arg)
}

// Math controller
type Math struct {
	erpc.CallCtx
}

// Divide handler
func (m *Math) Divide(arg *args.DivideArg) (*args.DivideResult, *erpc.Status) {
	return logic.Math_Divide(m.CallCtx, arg)
}
