// Code generated by 'micro gen' command.
// DO NOT EDIT!

package api

import (
	tp "github.com/henrylee2cn/teleport/v6"

	"github.com/xiaoenai/tp-micro/v6/examples/project/args"
	"github.com/xiaoenai/tp-micro/v6/examples/project/logic"
)

// Home handler
func Home(ctx tp.CallCtx, arg *args.EmptyStruct) (*args.HomeResult, *tp.Status) {
	return logic.Home(ctx, arg)
}

// Math controller
type Math struct {
	tp.CallCtx
}

// Divide handler
func (m *Math) Divide(arg *args.DivideArg) (*args.DivideResult, *tp.Status) {
	return logic.Math_Divide(m.CallCtx, arg)
}
