// Code generated by 'micro gen' command.
// DO NOT EDIT!

package api

import (
	tp "github.com/henrylee2cn/teleport"

	"github.com/xiaoenai/tp-micro/examples/project/args"
	"github.com/xiaoenai/tp-micro/examples/project/logic"
)

// Stat handler
func Stat(ctx tp.PushCtx, arg *args.StatArg) *tp.Rerror {
	return logic.Stat(ctx, arg)
}
