// Code generated by 'micro gen' command.
// DO NOT EDIT!

package args

// UserSql the statement to create 'user' mysql table
const UserSql string = ``

// LogSql the statement to create 'log' mysql table
const LogSql string = ``

// DeviceSql the statement to create 'device' mysql table
const DeviceSql string = ``
