// Code generated by 'micro gen' command.
// DO NOT EDIT!

package args

import (
	"github.com/xiaoenai/tp-micro/examples/project/logic/model"
)

// HomeResult home result
type HomeResult struct {
	Content string `json:"content"` // text
}

type (
	// DivideArg divide api arg
	DivideArg = model.DivideArg
	// DivideResult divide api result
	DivideResult struct {
		// quotient
		C float64 `json:"c"`
	}
)

// StatArg stat handler arg
type StatArg struct {
	Ts int64 `json:"ts"` // timestamps
}

// User user info
type User = model.User
