// Code generated by 'micro gen' command.
// The temporary code used to ensure successful compilation!
// When the project is completed, it should be removed!

package logic

import (
	"github.com/henrylee2cn/erpc/v6"

	"github.com/xiaoenai/tp-micro/examples/project/args"
	// "github.com/xiaoenai/tp-micro/examples/project/logic/model"
	// "github.com/xiaoenai/tp-micro/examples/project/errs"
)

// Stat handler
func Stat(ctx erpc.PushCtx, arg *args.StatArg) *erpc.Status {
	return nil
}

// Home handler
func Home(ctx erpc.CallCtx, arg *args.EmptyStruct) (*args.HomeResult, *erpc.Status) {
	return new(args.HomeResult), nil
}

// Divide handler
func Math_Divide(ctx erpc.CallCtx, arg *args.DivideArg) (*args.DivideResult, *erpc.Status) {
	return new(args.DivideResult), nil
}
