// Code generated by 'micro gen' command.
// DO NOT EDIT!

package main

import (
	tp "github.com/henrylee2cn/teleport"

	"github.com/xiaoenai/tp-micro/examples/project/internal/handler"
)

// route registers handlers to router.
func route(_root string, _router *tp.Router) {
	// root router group
	_group := _router.SubRoute(_root)

	// CALL APIs...
	{
		_group.RouteCallFunc(handler.Home)
		_group.RouteCall(new(handler.Math))
	}

	// PUSH APIs...
	{
		_group.RoutePushFunc(handler.Stat)
	}
}
