// Code generated by 'micro gen' command.
// DO NOT EDIT!

package sdk_test

import (
	"encoding/json"
	"fmt"

	tp "github.com/henrylee2cn/teleport"

	"github.com/xiaoenai/tp-micro/examples/project/sdk"
)

func toJsonBytes(i interface{}) []byte {
	b, _ := json.MarshalIndent(i, "", "  ")
	return b
}

func ExampleStat() {
	stat := sdk.Stat(nil, &sdk.StatArg{})
	if stat != nil {
		tp.Errorf("Stat: rerr: %s", toJsonBytes(stat))
	}
	fmt.Printf("")
	// Output:
}

func ExampleHome() {
	result, stat := sdk.Home(nil, &sdk.EmptyStruct{})
	if stat != nil {
		tp.Errorf("Home: rerr: %s", toJsonBytes(stat))
	} else {
		tp.Infof("Home: result: %s", toJsonBytes(result))
	}
	fmt.Printf("")
	// Output:
}

func ExampleMath_Divide() {
	result, stat := sdk.Math_Divide(nil, &sdk.DivideArg{})
	if stat != nil {
		tp.Errorf("Math_Divide: rerr: %s", toJsonBytes(stat))
	} else {
		tp.Infof("Math_Divide: result: %s", toJsonBytes(result))
	}
	fmt.Printf("")
	// Output:
}
