// Code generated by 'micro gen' command.
// DO NOT EDIT!

package sdk

import (
	"fmt"

	tp "github.com/henrylee2cn/teleport"
	"github.com/henrylee2cn/teleport/socket"
	micro "github.com/xiaoenai/tp-micro"
	"github.com/xiaoenai/tp-micro/discovery"
	"github.com/xiaoenai/tp-micro/model/etcd"

	"github.com/xiaoenai/tp-micro/examples/project/args"
)

var _ = fmt.Sprintf
var client *micro.Client

// Init initializes client with configs.
func Init(cliConfig micro.CliConfig, etcdConfing etcd.EasyConfig) {
	client = micro.NewClient(
		cliConfig,
		discovery.NewLinker(etcdConfing),
	)
}

// InitWithClient initializes client with specified object.
func InitWithClient(cli *micro.Client) {
	client = cli
}

// Stat handler
func Stat(arg *args.StatArg, setting ...socket.PacketSetting) *tp.Rerror {
	return client.Push(fmt.Sprintf("/project/stat?ts=%v", arg.Ts), arg, setting...)
}

// Home handler
func Home(arg *args.EmptyStruct, setting ...socket.PacketSetting) (*args.HomeResult, *tp.Rerror) {
	result := new(args.HomeResult)
	rerr := client.Call("/project/home", arg, result, setting...).Rerror()
	return result, rerr
}

// Divide handler
func Math_Divide(arg *args.DivideArg, setting ...socket.PacketSetting) (*args.DivideResult, *tp.Rerror) {
	result := new(args.DivideResult)
	rerr := client.Call("/project/math/divide", arg, result, setting...).Rerror()
	return result, rerr
}
