// Code generated by 'micro gen' command.
// DO NOT EDIT!

package sdk

import (
	"testing"

	tp "github.com/henrylee2cn/teleport"
	micro "github.com/xiaoenai/tp-micro"
	"github.com/xiaoenai/tp-micro/model/etcd"

	"github.com/xiaoenai/tp-micro/examples/project/args"
)

// TestSdk test SDK.
func TestSdk(t *testing.T) {
	Init(
		micro.CliConfig{
			Failover:        3,
			HeartbeatSecond: 4,
		},
		etcd.EasyConfig{
			Endpoints: []string{"http://127.0.0.1:2379"},
		},
	)

	{
		result, rerr := Home(new(struct{}))
		if rerr != nil {
			tp.Errorf("Home: rerr: %v", rerr)
		} else {
			tp.Infof("Home: result: %#v", result)
		}
	}
	{
		result, rerr := Math_Divide(new(args.DivideArg))
		if rerr != nil {
			tp.Errorf("Math_Divide: rerr: %v", rerr)
		} else {
			tp.Infof("Math_Divide: result: %#v", result)
		}
	}
	{
		rerr := Stat(new(args.StatArg))
		tp.Infof("Stat: rerr: %v", rerr)
	}
}
